{
  "displayName": "Java with Spring Boot and MySQL",
  "description": "Java stack with OpenJDK 8, MySQL and Spring Boot Petclinic demo application",
  "tags": [
    "community",
    "Java",
    "OpenJDK",
    "Maven",
    "Spring Boot",
    "MySQL"
  ],
  "icon": "/images/springboot.svg",
  "links": {
    "self": "/devfiles/java-mysql/devfile.yaml"
  }
}
