apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-idea-java-guestbook
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-idea-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: che-idea-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:49986fed7f4e2555a154c856795c689b8367206b63ec37426fe2c8e43f5630e4
        command:
          - /projector/entrypoint-volume.sh
        env:
          - name: PROJECTOR_ASSEMBLY_DIR
            value: /projector
          - name: PROJECTOR_CONFIG_DIR
            value: /home/user/.jetbrains
        volumeMounts:
          - name: projector-volume
            path: /projector
          - name: projector-configuration
            path: /home/user/.jetbrains
          - name: projector-java-configuration
            path: /home/user/.java
        memoryLimit: 6144Mi
        memoryRequest: 2048Mi
        cpuLimit: 2000m
        cpuRequest: 1500m
        endpoints:
          - name: intellij
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
              secure: false
            targetPort: 8887
            exposure: public
            path: /?backgroundColor=434343&wss
            protocol: http
          - name: intellij-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: intellij-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: intellij-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-idea-runtime
        app.kubernetes.io/part-of: che-idea.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: projector-volume
      volume: {}
    - name: projector-configuration
      volume: {}
    - name: projector-java-configuration
      volume: {}
    - name: che-idea-injector
      container:
        image: quay.io/che-incubator/che-idea:next
        command:
          - /projector/entrypoint-init-container.sh
        env:
          - name: PROJECTOR_VOLUME_MOUNT
            value: /projector-volume
          - name: PROJECTOR_ASSEMBLY_DIR
            value: /projector
        volumeMounts:
          - name: projector-volume
            path: /projector-volume
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: java-guestbook
spec:
  started: true
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          memoryLimit: 3Gi
          endpoints:
            - name: java-guestbook-backend
              exposure: public
              protocol: http
              targetPort: 8080
            - name: java-guestbook
              exposure: public
              protocol: http
              targetPort: 8443
            - name: debug
              exposure: none
              protocol: tcp
              targetPort: 5005
          volumeMounts:
            - name: m2
              path: /home/user/.m2
        attributes:
          controller.devfile.io/merge-contribution: true
      - name: mongo
        container:
          image: >-
            quay.io/eclipse/che--centos--mongodb-36-centos7:latest-ffdf2431bbc6d9a9d2a03e95bbbe8adb49ab9eac301f268a35038c84288259c1
          memoryLimit: 300Mi
          env:
            - name: MONGODB_USER
              value: user
            - name: MONGODB_PASSWORD
              value: password
            - name: MONGODB_DATABASE
              value: guestbook
            - name: MONGODB_ADMIN_PASSWORD
              value: password
          endpoints:
            - name: java-guestbook-mongodb
              exposure: none
              protocol: tcp
              targetPort: 27017
          volumeMounts:
            - name: mongodbdata
              path: /var/lib/mongodb/data
      - name: m2
        volume:
          size: 1G
      - name: mongodbdata
        volume:
          size: 256Mi
    commands:
      - id: maven-build-backend
        exec:
          label: build backend
          component: tools
          workingDir: ${PROJECT_SOURCE}/backend
          commandLine: mvn clean install
          group:
            kind: build
            isDefault: true
      - id: maven-build-frontend
        exec:
          label: build frontend
          component: tools
          workingDir: ${PROJECT_SOURCE}/frontend
          commandLine: mvn clean install
          group:
            kind: build
            isDefault: true
      - id: run-backend
        exec:
          label: run backend
          component: tools
          workingDir: ${PROJECT_SOURCE}/backend
          commandLine: >
            mvn spring-boot:run -DskipTests -Drun.jvmArguments='-Xdebug
            -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5006,quiet=y'
          group:
            kind: run
            isDefault: true
      - id: run-frontend
        exec:
          label: run frontend
          component: tools
          workingDir: ${PROJECT_SOURCE}/frontend
          commandLine: >
            mvn spring-boot:run -DskipTests -Drun.jvmArguments='-Xdebug
            -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005,quiet=y'
          group:
            kind: run
            isDefault: true
    projects:
      - name: java-guestbook
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/7.63.0/resources/v2/java-guestbook.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-idea-java-guestbook
