---
displayName: Bash
description: Stack with environment ready to develop bash scripts.
tags: ["Community", "Bash", "Shell"]
icon: /images/che.svg
links:
  v2: https://github.com/che-samples/bash/tree/devfilev2
