apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-react-web-app
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: che-code-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:d1709bbdfa076474f58f796026a2ed2dd3b24fea7e51ce2cc984e729663ff62c
        command:
          - /checode/entrypoint-volume.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 1024Mi
        memoryRequest: 256Mi
        cpuLimit: 500m
        cpuRequest: 30m
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            path: '?tkn=eclipse-che'
            secure: false
            protocol: https
          - name: code-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: code-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: code-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-code-runtime
        app.kubernetes.io/part-of: che-code.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: react-web-app
spec:
  started: true
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
          endpoints:
            - exposure: public
              name: nodejs
              protocol: http
              targetPort: 3000
          memoryLimit: 1G
          mountSources: true
        attributes:
          controller.devfile.io/merge-contribution: true
    commands:
      - id: install-dependencies
        exec:
          label: Install all required dependencies
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: yarn install
          group:
            kind: build
            isDefault: true
      - id: build
        exec:
          label: Build the app
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: yarn build
          group:
            kind: build
            isDefault: true
      - id: run
        exec:
          label: Run the web app
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: yarn start
          group:
            kind: run
      - id: test
        exec:
          label: Launch tests
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: yarn test
          group:
            kind: test
    projects:
      - name: react-web-app
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/react-web-app.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-code-react-web-app
