apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-quarkus-quickstart
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: quarkus-quickstart
spec:
  started: true
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-3055e6d
          env:
            - name: QUARKUS_HTTP_HOST
              value: 0.0.0.0
          endpoints:
            - exposure: none
              name: debug
              protocol: tcp
              targetPort: 5005
            - exposure: public
              name: hello-greeting-endpoint
              protocol: http
              targetPort: 8080
              path: /hello/greeting/che-user
            - name: che-code
              attributes:
                type: main
                cookiesAuthEnabled: true
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 3100
              exposure: public
              path: '?tkn=eclipse-che'
              secure: false
              protocol: https
            - name: code-redirect-1
              attributes:
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 13131
              exposure: public
              protocol: http
            - name: code-redirect-2
              attributes:
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 13132
              exposure: public
              protocol: http
            - name: code-redirect-3
              attributes:
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 13133
              exposure: public
              protocol: http
          volumeMounts:
            - name: m2
              path: /home/user/.m2
            - name: checode
              path: /checode
          memoryLimit: 5.77G
          mountSources: true
          command:
            - /checode/entrypoint-volume.sh
          memoryRequest: 256Mi
          cpuLimit: 500m
          cpuRequest: 30m
        attributes:
          che-code.eclipse.org/contribute-entry-point: true
          che-code.eclipse.org/contribute-volume-mount/checode: /checode
          che-code.eclipse.org/contribute-endpoint/che-code: 3100
          che-code.eclipse.org/contribute-endpoint/code-redirect-1: 13131
          che-code.eclipse.org/contribute-endpoint/code-redirect-2: 13132
          che-code.eclipse.org/contribute-endpoint/code-redirect-3: 13133
          che-code.eclipse.org/contribute-memoryLimit: true
          che-code.eclipse.org/original-memoryLimit: 4.7G
          che-code.eclipse.org/contribute-memoryRequest: true
          che-code.eclipse.org/contribute-cpuLimit: true
          che-code.eclipse.org/contribute-cpuRequest: true
          che-code.eclipse.org/contributed-container: tools
      - name: ubi-minimal
        container:
          image: registry.access.redhat.com/ubi8/ubi-minimal
          command:
            - tail
          args:
            - '-f'
            - /dev/null
          memoryLimit: 64M
          mountSources: true
      - name: m2
        volume:
          size: 1G
      - name: che-code-quarkus-quickstart
        plugin:
          kubernetes:
            name: che-code-quarkus-quickstart
    commands:
      - id: package
        exec:
          component: tools
          workingDir: ${PROJECT_SOURCE}/getting-started
          commandLine: mvn package
          group:
            kind: build
            isDefault: true
      - id: package-native
        exec:
          label: Package Native
          component: tools
          workingDir: ${PROJECT_SOURCE}/getting-started
          commandLine: >-
            mvn package -Dnative -Dmaven.test.skip
            -Dquarkus.native.native-image-xmx=2G
          group:
            kind: build
      - id: start-dev
        exec:
          label: Start Development mode (Hot reload + debug)
          component: tools
          workingDir: ${PROJECT_SOURCE}/getting-started
          commandLine: mvn compile quarkus:dev
          group:
            kind: run
            isDefault: true
      - id: start-native
        exec:
          label: Start Native
          component: ubi-minimal
          workingDir: ${PROJECT_SOURCE}/getting-started/target
          commandLine: ./getting-started-1.0.0-SNAPSHOT-runner
          group:
            kind: run
    projects:
      - name: quarkus-quickstarts
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/7.53.0/resources/v2/quarkus-quickstarts.zip'
