displayName: Java Lombok
description: Java Stack with Lombok 1.18.18, OpenJDK 11 and Maven 3.6.0
tags:
  - Community
  - Java
  - OpenJDK
  - Maven
  - Debian
  - Lombok
icon: /images/lombok.svg
links:
  v2: https://github.com/che-samples/lombok-project-sample/tree/main
  devWorkspaces:
    che-incubator/che-idea/next: /devfiles/java-lombok/devworkspace-che-idea-next.yaml
    che-incubator/che-code/latest: /devfiles/java-lombok/devworkspace-che-code-latest.yaml
    che-incubator/che-code/insiders: /devfiles/java-lombok/devworkspace-che-code-insiders.yaml
