displayName: PHP Symfony
description: PHP Stack with Symfony Demo Application https://symfony.com/
tags:
  - community
  - PHP
  - Apache
  - MySQL
  - Symfony
  - Debian
  - Centos
icon: /images/php.svg
links:
  v2: https://github.com/che-samples/php-symfony/tree/devfilev2
  self: /devfiles/php-symfony/devfile.yaml
  devWorkspaces:
    eclipse/che-theia/latest: /devfiles/php-symfony/devworkspace-che-theia-latest.yaml
    eclipse/che-theia/next: /devfiles/php-symfony/devworkspace-che-theia-next.yaml
