apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-idea-python-django
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-idea-injector
    - id: init-che-idea-command
      exec:
        component: che-idea-runtime-description
        commandLine: >-
          nohup /projector/entrypoint-volume.sh > /projector/entrypoint-logs.txt
          2>&1 &
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-idea-command
  components:
    - name: che-idea-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:75034f0dad7a6df3db53e20fc3597b68f2311e556164d47aa9151d3b3584bbce
        env:
          - name: PROJECTOR_ASSEMBLY_DIR
            value: /projector
          - name: PROJECTOR_CONFIG_DIR
            value: /home/user/.jetbrains
        volumeMounts:
          - name: projector-volume
            path: /projector
          - name: projector-configuration
            path: /home/user/.jetbrains
          - name: projector-java-configuration
            path: /home/user/.java
        memoryLimit: 6144Mi
        memoryRequest: 2048Mi
        cpuLimit: 2000m
        cpuRequest: 1500m
        endpoints:
          - name: intellij
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 8887
            exposure: public
            path: /?backgroundColor=434343&wss
            secure: true
            protocol: https
          - name: intellij-redirect-1
            targetPort: 13131
            exposure: public
            protocol: https
            attributes:
              discoverable: false
              urlRewriteSupported: false
          - name: intellij-redirect-2
            targetPort: 13132
            exposure: public
            protocol: https
            attributes:
              discoverable: false
              urlRewriteSupported: false
          - name: intellij-redirect-3
            targetPort: 13133
            exposure: public
            protocol: https
            attributes:
              discoverable: false
              urlRewriteSupported: false
      attributes:
        app.kubernetes.io/component: che-idea-runtime
        app.kubernetes.io/part-of: che-idea.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: projector-volume
      volume: {}
    - name: projector-configuration
      volume: {}
    - name: projector-java-configuration
      volume: {}
    - name: che-idea-injector
      container:
        image: quay.io/che-incubator/che-idea:next
        command:
          - /projector/entrypoint-init-container.sh
        env:
          - name: PROJECTOR_VOLUME_MOUNT
            value: /projector-volume
          - name: PROJECTOR_ASSEMBLY_DIR
            value: /projector
        volumeMounts:
          - name: projector-volume
            path: /projector-volume
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: python-django
  annotations:
    che.eclipse.org/devfile: |
      schemaVersion: 2.2.2
      metadata:
        name: python-django
      components:
        - name: tools
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-latest
            endpoints:
              - exposure: public
                name: django
                targetPort: 7000
                protocol: https
                path: /api
            volumeMounts:
              - name: venv
                path: /home/user/.venv
            memoryLimit: 512Mi
            mountSources: true
        - name: venv
          volume:
            size: 1G
      commands:
        - id: install-dependencies
          exec:
            label: Install dependencies
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: >-
              python3 -m venv .venv && . .venv/bin/activate && pip3 install -r
              requirements.txt && pip3 install ptvsd
            group:
              kind: build
        - id: migrate
          exec:
            label: Migrate
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: . .venv/bin/activate && python3 manage.py migrate
            group:
              kind: build
        - id: run
          exec:
            label: Run the server
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: >-
              . .venv/bin/activate && export DEBUG_MODE=False && python3 manage.py
              runserver 0.0.0.0:7000
            group:
              kind: run
        - id: debug
          exec:
            label: Run the server in debug mode
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: >-
              . .venv/bin/activate &&  export DEBUG_MODE=True && python3 manage.py
              runserver 0.0.0.0:7000 --noreload --nothreading
            group:
              kind: debug
      projects:
        - name: django-realworld-example-app
          zip:
            location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/django-realworld-example-app.zip'
spec:
  started: true
  routingClass: che
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          endpoints:
            - exposure: public
              name: django
              targetPort: 7000
              protocol: https
              path: /api
          volumeMounts:
            - name: venv
              path: /home/user/.venv
          memoryLimit: 512Mi
          mountSources: true
      - name: venv
        volume:
          size: 1G
    commands:
      - id: install-dependencies
        exec:
          label: Install dependencies
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: >-
            python3 -m venv .venv && . .venv/bin/activate && pip3 install -r
            requirements.txt && pip3 install ptvsd
          group:
            kind: build
      - id: migrate
        exec:
          label: Migrate
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: . .venv/bin/activate && python3 manage.py migrate
          group:
            kind: build
      - id: run
        exec:
          label: Run the server
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: >-
            . .venv/bin/activate && export DEBUG_MODE=False && python3 manage.py
            runserver 0.0.0.0:7000
          group:
            kind: run
      - id: debug
        exec:
          label: Run the server in debug mode
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: >-
            . .venv/bin/activate &&  export DEBUG_MODE=True && python3 manage.py
            runserver 0.0.0.0:7000 --noreload --nothreading
          group:
            kind: debug
    projects:
      - name: django-realworld-example-app
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/django-realworld-example-app.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-idea-python-django
