displayName: Python Django
description: Python Stack with Python 3.8 and Django application
tags:
  - Community
  - Centos
  - Python
  - pip
icon: /images/python.svg
links:
  v2: https://github.com/che-samples/django-realworld-example-app/tree/main
  devWorkspaces:
    che-incubator/che-idea/next: /devfiles/python-django/devworkspace-che-idea-next.yaml
    che-incubator/che-code/latest: /devfiles/python-django/devworkspace-che-code-latest.yaml
    che-incubator/che-code/insiders: /devfiles/python-django/devworkspace-che-code-insiders.yaml
