displayName: Java with Spring Boot and MongoDB
description: Java stack with OpenJDK 8, MongoDB and Spring Boot Guestbook demo application
tags:
  - Community
  - Java
  - OpenJDK
  - Maven
  - Spring Boot
  - MongoDB
icon: /images/java.svg
links:
  v2: https://github.com/che-samples/java-guestbook/tree/main
  devWorkspaces:
    che-incubator/che-idea/next: /devfiles/java-mongo/devworkspace-che-idea-next.yaml
    che-incubator/che-code/latest: /devfiles/java-mongo/devworkspace-che-code-latest.yaml
    che-incubator/che-code/insiders: /devfiles/java-mongo/devworkspace-che-code-insiders.yaml
