---
displayName: NodeJS React Web Application
description: Stack for developing NodeJS React Web Application
tags: ["NodeJS", "React", "Redux", "RealWorld"]
icon: /images/nodejs.svg
globalMemoryLimit: 1686Mi
