displayName: Java Gradle
description: Java Stack with OpenJDK 11 and Gradle 6.2.1
tags:
  - community
  - Java
  - OpenJDK
  - Gradle
  - Ubuntu
icon: /images/java.svg
links:
  self: /devfiles/java-gradle/devfile.yaml
