schemaVersion: 2.1.0
metadata:
  name: che-devfile-registry
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: devtools
    container:
      image: "quay.io/devfile/universal-developer-image:ubi8-latest"
      memoryLimit: 2Gi
      memoryRequest: 256Mi

