displayName: Java Vert.x
description: Java stack with OpenJDK 8 and Vert.x demo application
tags:
  - community
  - Java
  - OpenJDK
  - Maven
  - Vertx
icon: /images/vertx.svg
links:
  self: /devfiles/java-web-vertx/devfile.yaml
