---
displayName: Java Web Spring
description: Default Java Spring Stack
tags: ["Java", "Maven", "Spring Boot v2"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 2674Mi
