---
displayName: Java Spring Boot
description: Java stack with Spring Boot Petclinic demo application
tags: ["Community", "Java", "OpenJDK", "Maven", "Spring Boot"]
icon: /images/springboot.svg
links:
  v2: https://github.com/che-samples/java-spring-petclinic/tree/main
