#
# Copyright (c) 2018-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{ if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: che-devfile-registry
  labels:
    app.kubernetes.io/name: che
    app.kubernetes.io/component: devfile-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class }}
spec:
  rules:
  - host: {{ template "devfile.hostname" . -}} . {{- .Values.global.ingressDomain }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: ImplementationSpecific
        {{- else -}}
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: che-devfile-registry
            port:
              number: 8080
          {{- else }}
            serviceName: che-devfile-registry
            servicePort: 8080
          {{- end }}
{{- if .Values.cheDevfileRegistryIngressSecretName }}
  tls:
  - hosts:
    - {{ template "devfile.hostname" . -}} . {{- .Values.global.ingressDomain }}
    secretName: {{ .Values.cheDevfileRegistryIngressSecretName }}
{{- end -}}
