#
# Copyright (c) 2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-devfile-registry
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class }}
spec:
  rules:
  - host: {{ printf "che-devfile-registry-%s.%s" .Release.Namespace .Values.global.ingressDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: che-devfile-registry
          servicePort: 8080
{{- if .Values.cheDevfileRegistryIngressSecretName }}
  tls:
  - hosts:
    - {{ printf "che-devfile-registry-%s.%s" .Release.Namespace .Values.global.ingressDomain }}
    secretName: {{ .Values.cheDevfileRegistryIngressSecretName }}
{{- end -}}
