apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-quarkus-quickstart
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
    - id: init-che-code-command
      exec:
        component: che-code-runtime-description
        commandLine: >-
          nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
          2>&1 &
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-code-command
  components:
    - name: che-code-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:8a0f1295f1e1cdbc52da111cf90f735c00e445f9d99994bacdab9248bdfd1700
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 1024Mi
        memoryRequest: 256Mi
        cpuLimit: 500m
        cpuRequest: 30m
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: false
            protocol: https
          - name: code-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: code-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: code-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-code-runtime
        app.kubernetes.io/part-of: che-code.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 256Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: quarkus-quickstart
  annotations:
    che.eclipse.org/devfile: |
      schemaVersion: 2.1.0
      metadata:
        name: quarkus-quickstart
      components:
        - name: tools
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-latest
            env:
              - name: QUARKUS_HTTP_HOST
                value: 0.0.0.0
            endpoints:
              - exposure: none
                name: debug
                protocol: tcp
                targetPort: 5005
              - exposure: public
                name: hello-greeting-endpoint
                protocol: http
                targetPort: 8080
                path: /hello/greeting/che-user
            volumeMounts:
              - name: m2
                path: /home/user/.m2
            memoryLimit: 4.7G
            mountSources: true
        - name: ubi-minimal
          container:
            image: registry.access.redhat.com/ubi8/ubi-minimal
            command:
              - tail
            args:
              - '-f'
              - /dev/null
            memoryLimit: 64M
            mountSources: true
        - name: m2
          volume:
            size: 1G
      commands:
        - id: package
          exec:
            component: tools
            workingDir: ${PROJECT_SOURCE}/getting-started
            commandLine: mvn package
            group:
              kind: build
              isDefault: true
        - id: package-native
          exec:
            label: Package Native
            component: tools
            workingDir: ${PROJECT_SOURCE}/getting-started
            commandLine: >-
              mvn package -Dnative -Dmaven.test.skip
              -Dquarkus.native.native-image-xmx=2G
            group:
              kind: build
        - id: start-dev
          exec:
            label: Start Development mode (Hot reload + debug)
            component: tools
            workingDir: ${PROJECT_SOURCE}/getting-started
            commandLine: mvn compile quarkus:dev
            group:
              kind: run
              isDefault: true
        - id: start-native
          exec:
            label: Start Native
            component: ubi-minimal
            workingDir: ${PROJECT_SOURCE}/getting-started/target
            commandLine: ./getting-started-1.0.0-SNAPSHOT-runner
            group:
              kind: run
      projects:
        - name: quarkus-quickstarts
          zip:
            location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/quarkus-quickstarts.zip'
spec:
  started: true
  routingClass: che
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          env:
            - name: QUARKUS_HTTP_HOST
              value: 0.0.0.0
          endpoints:
            - exposure: none
              name: debug
              protocol: tcp
              targetPort: 5005
            - exposure: public
              name: hello-greeting-endpoint
              protocol: http
              targetPort: 8080
              path: /hello/greeting/che-user
          volumeMounts:
            - name: m2
              path: /home/user/.m2
          memoryLimit: 4.7G
          mountSources: true
      - name: ubi-minimal
        container:
          image: registry.access.redhat.com/ubi8/ubi-minimal
          command:
            - tail
          args:
            - '-f'
            - /dev/null
          memoryLimit: 64M
          mountSources: true
      - name: m2
        volume:
          size: 1G
    commands:
      - id: package
        exec:
          component: tools
          workingDir: ${PROJECT_SOURCE}/getting-started
          commandLine: mvn package
          group:
            kind: build
            isDefault: true
      - id: package-native
        exec:
          label: Package Native
          component: tools
          workingDir: ${PROJECT_SOURCE}/getting-started
          commandLine: >-
            mvn package -Dnative -Dmaven.test.skip
            -Dquarkus.native.native-image-xmx=2G
          group:
            kind: build
      - id: start-dev
        exec:
          label: Start Development mode (Hot reload + debug)
          component: tools
          workingDir: ${PROJECT_SOURCE}/getting-started
          commandLine: mvn compile quarkus:dev
          group:
            kind: run
            isDefault: true
      - id: start-native
        exec:
          label: Start Native
          component: ubi-minimal
          workingDir: ${PROJECT_SOURCE}/getting-started/target
          commandLine: ./getting-started-1.0.0-SNAPSHOT-runner
          group:
            kind: run
    projects:
      - name: quarkus-quickstarts
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/quarkus-quickstarts.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-code-quarkus-quickstart
