---
displayName: Apache Camel based projects on Che 7
description: Stack with environment ready to develop Integration projects with Apache Camel based on SpringBoot.
tags: ["Java", "OpenJDK", "Maven", "Debian", "Apache Camel", "Red Hat Fuse"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 2930Mi
