---
displayName: Apache Camel based projects on Che 7
description: Stack with environment ready to develop Integration projects with Apache Camel based on SpringBoot.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
