apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-apache-camel-springboot
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: apache-camel-springboot
spec:
  started: true
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
          memoryLimit: 4Gi
          endpoints:
            - exposure: none
              name: debug
              protocol: tcp
              targetPort: 5005
            - exposure: public
              name: 8080-tcp
              protocol: http
              targetPort: 8080
            - name: che-code
              attributes:
                type: main
                cookiesAuthEnabled: true
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 3100
              exposure: public
              path: '?tkn=eclipse-che'
              secure: false
              protocol: https
            - name: code-redirect-1
              attributes:
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 13131
              exposure: public
              protocol: http
            - name: code-redirect-2
              attributes:
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 13132
              exposure: public
              protocol: http
            - name: code-redirect-3
              attributes:
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 13133
              exposure: public
              protocol: http
          volumeMounts:
            - name: m2
              path: /home/user/.m2
            - name: checode
              path: /checode
          command:
            - /checode/entrypoint-volume.sh
          memoryRequest: 256Mi
          cpuLimit: 500m
          cpuRequest: 30m
        attributes:
          che-code.eclipse.org/contribute-entry-point: true
          che-code.eclipse.org/contribute-volume-mount/checode: /checode
          che-code.eclipse.org/contribute-endpoint/che-code: 3100
          che-code.eclipse.org/contribute-endpoint/code-redirect-1: 13131
          che-code.eclipse.org/contribute-endpoint/code-redirect-2: 13132
          che-code.eclipse.org/contribute-endpoint/code-redirect-3: 13133
          che-code.eclipse.org/contribute-memoryLimit: true
          che-code.eclipse.org/original-memoryLimit: 3Gi
          che-code.eclipse.org/contribute-memoryRequest: true
          che-code.eclipse.org/contribute-cpuLimit: true
          che-code.eclipse.org/contribute-cpuRequest: true
          che-code.eclipse.org/contributed-container: tools
      - name: m2
        volume:
          size: 1G
      - name: che-code-apache-camel-springboot
        plugin:
          kubernetes:
            name: che-code-apache-camel-springboot
    commands:
      - id: build-project
        exec:
          commandLine: JAVA_HOME=$JAVA_HOME_8 mvn clean install
          component: tools
          workingDir: ${PROJECT_SOURCE}
      - id: run-services
        exec:
          commandLine: JAVA_HOME=$JAVA_HOME_8 mvn spring-boot:run -DskipTests
          component: tools
          workingDir: ${PROJECT_SOURCE}
      - id: debug-services
        exec:
          commandLine: >
            JAVA_HOME=$JAVA_HOME_8 mvn spring-boot:run -DskipTests \

            -Drun.jvmArguments="-Xdebug
            -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
          component: tools
          workingDir: ${PROJECT_SOURCE}
    projects:
      - name: fuse-rest-http-booster
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/7.44.0/resources/v2/fuse-rest-http-booster.zip'
