apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-dotnet
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
    - id: init-che-code-command
      exec:
        component: che-code-runtime-description
        commandLine: >-
          nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
          2>&1 &
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-code-command
  components:
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 256Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
    - name: che-code-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:75034f0dad7a6df3db53e20fc3597b68f2311e556164d47aa9151d3b3584bbce
        memoryLimit: 1024Mi
        memoryRequest: 256Mi
        cpuLimit: 500m
        cpuRequest: 30m
        volumeMounts:
          - name: checode
            path: /checode
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: true
            protocol: https
          - name: code-redirect-1
            targetPort: 13131
            exposure: public
            protocol: https
            attributes:
              discoverable: false
              urlRewriteSupported: false
          - name: code-redirect-2
            targetPort: 13132
            exposure: public
            protocol: https
            attributes:
              discoverable: false
              urlRewriteSupported: false
          - name: code-redirect-3
            targetPort: 13133
            exposure: public
            protocol: https
            attributes:
              discoverable: false
              urlRewriteSupported: false
      attributes:
        app.kubernetes.io/component: che-code-runtime
        app.kubernetes.io/part-of: che-code.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: checode
      volume: {}
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: dotnet
  annotations:
    che.eclipse.org/devfile: |
      schemaVersion: 2.2.0
      metadata:
        name: dotnet
      components:
        - name: tools
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-latest
            memoryLimit: 2Gi
            mountSources: true
            env:
              - name: CONFIGURATION
                value: Debug
              - name: STARTUP_PROJECT
                value: app.csproj
              - name: ASPNETCORE_ENVIRONMENT
                value: Development
              - name: ASPNETCORE_URLS
                value: http://*:8080
            endpoints:
              - name: https-dotnet60
                targetPort: 8080
                protocol: https
            volumeMounts:
              - name: nuget
                path: /home/user/.nuget
        - name: nuget
          volume:
            size: 1G
      commands:
        - id: build
          exec:
            label: Build
            component: tools
            workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
            commandLine: >-
              dotnet build -c $CONFIGURATION $STARTUP_PROJECT
              /p:UseSharedCompilation=false
            group:
              kind: build
        - id: run
          exec:
            label: Run
            component: tools
            workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
            commandLine: >-
              dotnet run -c $CONFIGURATION --no-build --project $STARTUP_PROJECT
              --no-launch-profile
            group:
              kind: run
      projects:
        - name: dotnet-web-simple
          zip:
            location: 'https://eclipse-che.github.io/che-devfile-registry/7.82.0/resources/v2/dotnet-web-simple.zip'
spec:
  started: true
  routingClass: che
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          memoryLimit: 2Gi
          mountSources: true
          env:
            - name: CONFIGURATION
              value: Debug
            - name: STARTUP_PROJECT
              value: app.csproj
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://*:8080
          endpoints:
            - name: https-dotnet60
              targetPort: 8080
              protocol: https
          volumeMounts:
            - name: nuget
              path: /home/user/.nuget
      - name: nuget
        volume:
          size: 1G
    commands:
      - id: build
        exec:
          label: Build
          component: tools
          workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
          commandLine: >-
            dotnet build -c $CONFIGURATION $STARTUP_PROJECT
            /p:UseSharedCompilation=false
          group:
            kind: build
      - id: run
        exec:
          label: Run
          component: tools
          workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
          commandLine: >-
            dotnet run -c $CONFIGURATION --no-build --project $STARTUP_PROJECT
            --no-launch-profile
          group:
            kind: run
    projects:
      - name: dotnet-web-simple
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/7.82.0/resources/v2/dotnet-web-simple.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-code-dotnet
