apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-nodejs-mongodb
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: nodejs-mongodb
spec:
  started: true
  template:
    components:
      - name: nodejs
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-b452131
          env:
            - name: SECRET
              value: 220fd770-c028-480d-8f95-f84353c7d55a
            - name: NODE_ENV
              value: production
          endpoints:
            - exposure: public
              name: nodejs
              targetPort: 8080
            - name: che-code
              attributes:
                type: main
                cookiesAuthEnabled: true
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 3100
              exposure: public
              path: '?tkn=eclipse-che'
              secure: false
              protocol: https
          memoryLimit: 2.07G
          mountSources: true
          command:
            - /checode/entrypoint-volume.sh
          volumeMounts:
            - name: checode
              path: /checode
          memoryRequest: 256Mi
          cpuLimit: 500m
          cpuRequest: 30m
        attributes:
          che-code.eclipse.org/contribute-entry-point: true
          che-code.eclipse.org/contribute-volume-mount/checode: /checode
          che-code.eclipse.org/contribute-endpoint/che-code: 3100
          che-code.eclipse.org/contribute-memoryLimit: true
          che-code.eclipse.org/original-memoryLimit: 1G
          che-code.eclipse.org/contribute-memoryRequest: true
          che-code.eclipse.org/contribute-cpuLimit: true
          che-code.eclipse.org/contribute-cpuRequest: true
          che-code.eclipse.org/contributed-container: nodejs
      - name: mongo
        container:
          image: >-
            quay.io/eclipse/che--centos--mongodb-36-centos7:latest-a915db7beca87198fcd7860086989fe8a327a1a4f6508025b64ab28fcc7423b2
          env:
            - name: MONGODB_USER
              value: user
            - name: MONGODB_PASSWORD
              value: password
            - name: MONGODB_DATABASE
              value: guestbook
            - name: MONGODB_ADMIN_PASSWORD
              value: password
          endpoints:
            - name: mongodb
              exposure: internal
              targetPort: 27017
              attributes:
                discoverable: 'true'
          memoryLimit: 512Mi
          mountSources: true
          volumeMounts:
            - name: mongo-storage
              path: /var/lib/mongodb/data
      - name: mongo-storage
        volume:
          size: 1G
      - name: che-code-nodejs-mongodb
        plugin:
          kubernetes:
            name: che-code-nodejs-mongodb
    commands:
      - id: runapp
        exec:
          label: Run the application
          component: nodejs
          workingDir: ${PROJECTS_ROOT}/nodejs-mongodb-sample
          commandLine: npm install && node --inspect=9229 app.js
          group:
            kind: run
    projects:
      - name: nodejs-mongodb-sample
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/nodejs-mongodb-sample.zip'
