apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-nodejs-mongodb
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
    - id: init-che-code-command
      exec:
        component: che-code-runtime-description
        commandLine: >-
          nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
          2>&1 &
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-code-command
  components:
    - name: che-code-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:80d07a6b85cdc34f76c8f9a4ea7a2ac3a409e6bc104d3933d97c0f51d7d05f63
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 1024Mi
        memoryRequest: 256Mi
        cpuLimit: 500m
        cpuRequest: 30m
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: false
            protocol: https
          - name: code-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: code-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: code-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-code-runtime
        app.kubernetes.io/part-of: che-code.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 256Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: nodejs-mongodb
  annotations:
    che.eclipse.org/devfile: |
      schemaVersion: 2.1.0
      metadata:
        name: nodejs-mongodb
      components:
        - name: tools
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-latest
            env:
              - name: SECRET
                value: 220fd770-c028-480d-8f95-f84353c7d55a
              - name: NODE_ENV
                value: production
            endpoints:
              - exposure: public
                name: nodejs
                targetPort: 8080
            memoryLimit: 1G
            mountSources: true
        - name: mongo
          container:
            image: >-
              quay.io/eclipse/che--centos--mongodb-36-centos7:latest-a915db7beca87198fcd7860086989fe8a327a1a4f6508025b64ab28fcc7423b2
            env:
              - name: MONGODB_USER
                value: user
              - name: MONGODB_PASSWORD
                value: password
              - name: MONGODB_DATABASE
                value: guestbook
              - name: MONGODB_ADMIN_PASSWORD
                value: password
            endpoints:
              - name: mongodb
                exposure: internal
                targetPort: 27017
                attributes:
                  discoverable: 'true'
            memoryLimit: 512Mi
            mountSources: true
            volumeMounts:
              - name: mongo-storage
                path: /var/lib/mongodb/data
        - name: mongo-storage
          volume:
            size: 256Mi
      commands:
        - id: run-application
          exec:
            label: Run the application
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: npm install && node --inspect=9229 app.js
            group:
              kind: run
      projects:
        - name: nodejs-mongodb-sample
          zip:
            location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/nodejs-mongodb-sample.zip'
spec:
  started: true
  routingClass: che
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          env:
            - name: SECRET
              value: 220fd770-c028-480d-8f95-f84353c7d55a
            - name: NODE_ENV
              value: production
          endpoints:
            - exposure: public
              name: nodejs
              targetPort: 8080
          memoryLimit: 1G
          mountSources: true
      - name: mongo
        container:
          image: >-
            quay.io/eclipse/che--centos--mongodb-36-centos7:latest-a915db7beca87198fcd7860086989fe8a327a1a4f6508025b64ab28fcc7423b2
          env:
            - name: MONGODB_USER
              value: user
            - name: MONGODB_PASSWORD
              value: password
            - name: MONGODB_DATABASE
              value: guestbook
            - name: MONGODB_ADMIN_PASSWORD
              value: password
          endpoints:
            - name: mongodb
              exposure: internal
              targetPort: 27017
              attributes:
                discoverable: 'true'
          memoryLimit: 512Mi
          mountSources: true
          volumeMounts:
            - name: mongo-storage
              path: /var/lib/mongodb/data
      - name: mongo-storage
        volume:
          size: 256Mi
    commands:
      - id: run-application
        exec:
          label: Run the application
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: npm install && node --inspect=9229 app.js
          group:
            kind: run
    projects:
      - name: nodejs-mongodb-sample
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/nodejs-mongodb-sample.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-code-nodejs-mongodb
