displayName: Node.js MongoDB Web Application
description: Stack with NodeJS 10 and MongoDB 3.4
tags:
  - Community
  - Node.js
  - Express
  - MongoDB
  - RealWorld
  - ubi8
  - Centos
icon: /images/nodejs.svg
links:
  v2: https://github.com/che-samples/nodejs-mongodb-sample/tree/main
  devWorkspaces:
    che-incubator/che-idea/next: /devfiles/nodejs-mongo/devworkspace-che-idea-next.yaml
    che-incubator/che-code/latest: /devfiles/nodejs-mongo/devworkspace-che-code-latest.yaml
    che-incubator/che-code/insiders: /devfiles/nodejs-mongo/devworkspace-che-code-insiders.yaml
