#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# che-quarkus
# quay.io/quarkus/centos-quarkus-maven:21.0-java11
# quay.io/quarkus/centos-quarkus-maven@sha256:c472acf9e8ef7f722469a8dc37a7a2dfed220cfb22b9fe36a051fe80c153448f

ARG BASE_IMAGE="quay.io/quarkus/centos-quarkus-maven:21.0-java11"

FROM quay.io/quarkus/centos-quarkus-maven@sha256:e55016fa1c14d7aec39d6d91fff89c553458e226aa517352f58945b552be14a3

#{INCLUDE:../base.dockerfile}
