---
displayName: Python Django
description: Python Stack with Python 3.8 and Django application
tags: ["Community", "Centos", "Python", "pip"]
icon: /images/python.svg
links:
  v2: https://github.com/che-samples/django-realworld-example-app/tree/main
