---
displayName: Python Django
description: Python Stack with Python 3.7 and Django application
tags: ["Centos", "Python", "pip"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 1686Mi
