---
displayName: "PHP Simple"
description: PHP Stack with PHP 7.1 and simple web application
tags: ["PHP", "Apache", "Debian"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 2430Mi
