displayName: Java Spring Boot
description: Java stack with OpenJDK 11 and Spring Boot Petclinic demo application
tags:
  - Community
  - Java
  - OpenJDK
  - Maven
  - Spring Boot
icon: /images/springboot.svg
links:
  v2: https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
  devWorkspaces:
    eclipse/che-theia/latest: /devfiles/java-web-spring/devworkspace-che-theia-latest.yaml
    che-incubator/che-code/insiders: /devfiles/java-web-spring/devworkspace-che-code-insiders.yaml
