displayName: Go
description: Stack with Go 1.14
tags:
  - Community
  - Debian
  - Go
icon: /images/go.svg
links:
  v2: https://github.com/che-samples/golang-example/tree/devfilev2
  self: /devfiles/go/devfile.yaml
  devWorkspaces:
    eclipse/che-theia/latest: /devfiles/go/devworkspace-che-theia-latest.yaml
    eclipse/che-theia/next: /devfiles/go/devworkspace-che-theia-next.yaml
    che-incubator/che-code/insiders: /devfiles/go/devworkspace-che-code-insiders.yaml
