displayName: Rust
description: Rust Stack with Rust 1.57
tags:
  - Community
  - Rust
icon: /images/rust.svg
links:
  v2: https://github.com/che-samples/helloworld-rust/tree/devfilev2
  devWorkspaces:
    eclipse/che-theia/latest: /devfiles/rust/devworkspace-che-theia-latest.yaml
    che-incubator/che-code/insiders: /devfiles/rust/devworkspace-che-code-insiders.yaml
