displayName: Scala
description: Scala Stack with OpenJDK 11 and sbt 1.x
tags:
  - Community
  - Scala
  - OpenJDK
  - sbt
  - Debian
icon: /images/scala.svg
links:
  v2: https://github.com/che-samples/scala-sbt/tree/devfilev2
  devWorkspaces:
    eclipse/che-theia/latest: /devfiles/scala-sbt/devworkspace-che-theia-latest.yaml
    che-incubator/che-code/insiders: /devfiles/scala-sbt/devworkspace-che-code-insiders.yaml
