apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-python-hello-world
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
    - id: init-che-code-command
      exec:
        component: che-code-runtime-description
        commandLine: >-
          nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
          2>&1 &
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-code-command
  components:
    - name: che-code-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:2e629c52dbe236bc0a28f854920e5992a5b6272a47806462b1e9744970e811d1
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 1024Mi
        memoryRequest: 256Mi
        cpuLimit: 500m
        cpuRequest: 30m
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: false
            protocol: https
          - name: code-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: code-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: code-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-code-runtime
        app.kubernetes.io/part-of: che-code.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: >-
          quay.io/che-incubator/che-code@sha256:857079b48678762a3cf5afe22694e634c98d6d3b58148436b88945938d5d24e5
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 256Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: python-hello-world
  annotations:
    che.eclipse.org/devfile: |
      schemaVersion: 2.1.0
      metadata:
        name: python-hello-world
      components:
        - name: tools
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-latest
            volumeMounts:
              - name: venv
                path: /home/user/.venv
            memoryLimit: 512Mi
            mountSources: true
        - name: venv
          volume:
            size: 1G
      commands:
        - id: run-application
          exec:
            label: Run application
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: python3 hello-world.py
            group:
              kind: run
      projects:
        - name: python-hello-world
          zip:
            location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/python-hello-world.zip'
spec:
  started: true
  routingClass: che
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          volumeMounts:
            - name: venv
              path: /home/user/.venv
          memoryLimit: 512Mi
          mountSources: true
      - name: venv
        volume:
          size: 1G
    commands:
      - id: run-application
        exec:
          label: Run application
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: python3 hello-world.py
          group:
            kind: run
    projects:
      - name: python-hello-world
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/python-hello-world.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-code-python-hello-world
