apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-php-symfony
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
    - id: init-che-code-command
      exec:
        component: che-code-runtime-description
        commandLine: >-
          nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
          2>&1 &
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-code-command
  components:
    - name: che-code-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:98264e81d11bcfd74d46fd2037f5d26ee37794bb57b033328f35d838642e297f
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 1024Mi
        memoryRequest: 256Mi
        cpuLimit: 500m
        cpuRequest: 30m
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: false
            protocol: https
          - name: code-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: code-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: code-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-code-runtime
        app.kubernetes.io/part-of: che-code.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: >-
          quay.io/che-incubator/che-code@sha256:018394d5100c79d532ea0baf5ed0e902783b33ca57c7fb862108e3d688d97d84
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 256Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: php-symfony
spec:
  started: true
  routingClass: che
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          endpoints:
            - exposure: public
              name: symfony
              protocol: http
              targetPort: 8000
          memoryLimit: 2G
          mountSources: true
          volumeMounts:
            - name: composer
              path: /home/user/.composer
            - name: symfony
              path: /home/user/.symfony5
        attributes:
          controller.devfile.io/merge-contribution: true
      - name: composer
        volume:
          size: 512Mi
      - name: symfony
        volume:
          size: 512Mi
      - name: mysql
        container:
          image: >-
            quay.io/eclipse/che--centos--mysql-57-centos7:latest-e08ee4d43b7356607685b69bde6335e27cf20c020f345b6c6c59400183882764
          memoryLimit: 300Mi
          endpoints:
            - exposure: internal
              name: db
              protocol: tcp
              targetPort: 3306
          env:
            - name: MYSQL_USER
              value: db_user
            - name: MYSQL_PASSWORD
              value: db_password
            - name: MYSQL_DATABASE
              value: db_name
            - name: MYSQL_ROOT_PASSWORD
              value: db_password
          mountSources: false
    commands:
      - id: install-dependencies
        exec:
          label: Install dependencies
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: >-
            composer install && wget https://get.symfony.com/cli/installer -O -
            | bash
          group:
            kind: build
      - id: start-web-server
        exec:
          label: Start Symfony Web Server
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: $HOME/.symfony5/bin/symfony server:start
          group:
            kind: run
      - id: stop-web-server
        exec:
          label: Stop Symfony Web Server
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: $HOME/.symfony5/bin/symfony server:stop
          group:
            kind: run
    projects:
      - name: php-symfony
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/7.67.0/resources/v2/php-symfony.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-code-php-symfony
