displayName: Bash
description: Stack with environment ready to develop bash scripts.
tags:
  - Community
  - Bash
  - Shell
icon: /images/che.svg
links:
  v2: https://github.com/che-samples/bash/tree/main
  devWorkspaces:
    eclipse/che-theia/latest: /devfiles/bash/devworkspace-che-theia-latest.yaml
    eclipse/che-idea/next: /devfiles/bash/devworkspace-che-idea-next.yaml
    che-incubator/che-code/insiders: /devfiles/bash/devworkspace-che-code-insiders.yaml
