{
  "displayName": "Bash",
  "description": "Stack with environment ready to develop bash scripts.",
  "tags": [
    "Bash",
    "Shell"
  ],
  "icon": "/images/che.svg",
  "links": {
    "v2": "https://github.com/che-samples/bash/tree/devfilev2",
    "self": "/devfiles/bash/devfile.yaml",
    "devWorkspaces": {
      "eclipse/che-theia/latest": "/devfiles/bash/devworkspace-che-theia-latest.yaml",
      "eclipse/che-theia/next": "/devfiles/bash/devworkspace-che-theia-next.yaml"
    }
  }
}
