displayName: Node.js Web Application based on Yarn
description: Stack for developing Node.js Web Application based on Yarn
tags:
  - Community
  - Node.js
  - Alpine
  - Yarn
  - React
icon: /images/nodejs.svg
links:
  v2: https://github.com/che-samples/react-web-app/tree/main
  devWorkspaces:
    che-incubator/che-idea/next: /devfiles/nodejs-yarn/devworkspace-che-idea-next.yaml
    che-incubator/che-code/latest: /devfiles/nodejs-yarn/devworkspace-che-code-latest.yaml
    che-incubator/che-code/insiders: /devfiles/nodejs-yarn/devworkspace-che-code-insiders.yaml
