apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-spring-petclinic
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: spring-petclinic
spec:
  started: true
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-d433ed6
          memoryLimit: 4Gi
          endpoints:
            - exposure: none
              name: debug
              protocol: tcp
              targetPort: 5005
            - exposure: public
              name: 8080-tcp
              protocol: http
              targetPort: 8080
            - name: che-code
              attributes:
                type: main
                cookiesAuthEnabled: true
                discoverable: false
                urlRewriteSupported: true
                contributed-by: che-code.eclipse.org
              targetPort: 3100
              exposure: public
              path: '?tkn=eclipse-che'
              secure: false
              protocol: https
          volumeMounts:
            - name: m2
              path: /home/user/.m2
            - name: checode
              path: /checode
          command:
            - /checode/entrypoint-volume.sh
          memoryRequest: 256Mi
          cpuLimit: 500m
          cpuRequest: 30m
        attributes:
          che-code.eclipse.org/contribute-entry-point: true
          che-code.eclipse.org/contribute-volume-mount/checode: /checode
          che-code.eclipse.org/contribute-endpoint/che-code: 3100
          che-code.eclipse.org/contribute-memoryLimit: true
          che-code.eclipse.org/original-memoryLimit: 3Gi
          che-code.eclipse.org/contribute-memoryRequest: true
          che-code.eclipse.org/contribute-cpuLimit: true
          che-code.eclipse.org/contribute-cpuRequest: true
          che-code.eclipse.org/contributed-container: tools
      - name: m2
        volume:
          size: 1G
      - name: mysql
        container:
          image: >-
            quay.io/eclipse/che--centos--mysql-57-centos7:latest-e08ee4d43b7356607685b69bde6335e27cf20c020f345b6c6c59400183882764
          memoryLimit: 300Mi
          endpoints:
            - exposure: none
              name: db
              protocol: tcp
              targetPort: 3306
          env:
            - name: MYSQL_USER
              value: petclinic
            - name: MYSQL_PASSWORD
              value: petclinic
            - name: MYSQL_DATABASE
              value: petclinic
            - name: PS1
              value: $(echo ${0})\\$
      - name: che-code-spring-petclinic
        plugin:
          kubernetes:
            name: che-code-spring-petclinic
    commands:
      - id: prepare-database
        exec:
          component: mysql
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: >
            /opt/rh/rh-mysql57/root/usr/bin/mysql -u root <
            ${PROJECTS_ROOT}/java-spring-petclinic/src/main/resources/db/mysql/user.sql
            && \

            /opt/rh/rh-mysql57/root/usr/bin/mysql -u root petclinic <
            ${PROJECTS_ROOT}/java-spring-petclinic/src/main/resources/db/mysql/schema.sql
            && \

            /opt/rh/rh-mysql57/root/usr/bin/mysql -u root petclinic <
            ${PROJECTS_ROOT}/java-spring-petclinic/src/main/resources/db/mysql/data.sql
            && \

            echo -e "\e[32mDone.\e[0m Database petclinic was configured"
          group:
            kind: run
            isDefault: true
      - id: build
        exec:
          component: tools
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: mvn clean install
          group:
            kind: build
            isDefault: true
      - id: run-with-hsqldb
        exec:
          component: tools
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: java -jar target/*.jar
          group:
            kind: run
            isDefault: true
      - id: run-with-mysql
        exec:
          component: tools
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: >
            java -jar -Dspring-boot.run.profiles=mysql \

            -Xdebug
            -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 \

            target/*.jar
          group:
            kind: run
            isDefault: true
      - id: run-debug
        exec:
          component: tools
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: >-
            java -jar -Xdebug
            -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
            target/*.jar
          group:
            kind: run
            isDefault: true
    projects:
      - name: java-spring-petclinic
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/7.41.2/resources/v2/java-spring-petclinic.zip'
