#
# Copyright (c) 2019-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

ARG BASE_IMAGE="quay.io/eclipse/che-php-base:7.4-9c00f7a"

FROM quay.io/eclipse/che-php-base@sha256:da8cc8cd3e6d4615d00e29ff303490e95709a03a60515f8d1c9642f0784695d4

#{INCLUDE:../base.dockerfile}

