apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-scala-sbt
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
    - id: init-che-code-command
      exec:
        component: che-code-runtime-description
        commandLine: >-
          nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
          2>&1 &
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-code-command
  components:
    - name: che-code-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:5766879aa42f7d6d0434622cfec558ea4940b35e226e9380357de04b891bd840
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 1024Mi
        memoryRequest: 256Mi
        cpuLimit: 500m
        cpuRequest: 30m
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: false
            protocol: https
          - name: code-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: code-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: code-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-code-runtime
        app.kubernetes.io/part-of: che-code.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 256Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: scala-sbt
  annotations:
    che.eclipse.org/devfile: |
      schemaVersion: 2.1.0
      metadata:
        name: scala-sbt
      components:
        - name: tools
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-latest
            env:
              - name: JDK_JAVA_OPTIONS
                value: >-
                  -XX:MaxRAMPercentage=80 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
                  -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
                  -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
                  -Xms20m -Djava.security.egd=file:/dev/./urandom
            endpoints:
              - exposure: none
                name: debug
                protocol: tcp
                targetPort: 5005
              - exposure: public
                name: 8080-tcp
                protocol: http
                targetPort: 8080
            volumeMounts:
              - name: sbt
                path: /home/user/.sbt
              - name: ivy2
                path: /home/user/.ivy2
              - name: cache
                path: /home/user/.cache
              - name: coursier
                path: /home/user/.cache/coursier
              - name: metals
                path: /home/user/.cache/metals
              - name: bloop
                path: /home/user/.cache/bloop
            memoryLimit: 5Gi
            mountSources: true
        - name: sbt
          volume:
            size: 1G
        - name: ivy2
          volume:
            size: 1G
        - name: cache
          volume:
            size: 1G
        - name: coursier
          volume:
            size: 1G
        - name: metals
          volume:
            size: 1G
        - name: bloop
          volume:
            size: 1G
      commands:
        - id: build
          exec:
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: ./sbt +Test/compile
            group:
              kind: build
              isDefault: true
        - id: package
          exec:
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: ./sbt +publishLocal
            group:
              kind: build
        - id: sbt-repl
          exec:
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: ./sbt
            group:
              kind: run
        - id: run
          exec:
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: ./sbt run
            group:
              kind: run
              isDefault: true
        - id: test
          exec:
            component: tools
            workingDir: ${PROJECT_SOURCE}
            commandLine: ./sbt +test
            group:
              kind: run
      projects:
        - name: scala-sbt
          zip:
            location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/scala-sbt.zip'
spec:
  started: true
  routingClass: che
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -XX:MaxRAMPercentage=80 -XX:+UseParallelGC
                -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
                -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
                -Dsun.zip.disableMemoryMapping=true -Xms20m
                -Djava.security.egd=file:/dev/./urandom
          endpoints:
            - exposure: none
              name: debug
              protocol: tcp
              targetPort: 5005
            - exposure: public
              name: 8080-tcp
              protocol: http
              targetPort: 8080
          volumeMounts:
            - name: sbt
              path: /home/user/.sbt
            - name: ivy2
              path: /home/user/.ivy2
            - name: cache
              path: /home/user/.cache
            - name: coursier
              path: /home/user/.cache/coursier
            - name: metals
              path: /home/user/.cache/metals
            - name: bloop
              path: /home/user/.cache/bloop
          memoryLimit: 5Gi
          mountSources: true
      - name: sbt
        volume:
          size: 1G
      - name: ivy2
        volume:
          size: 1G
      - name: cache
        volume:
          size: 1G
      - name: coursier
        volume:
          size: 1G
      - name: metals
        volume:
          size: 1G
      - name: bloop
        volume:
          size: 1G
    commands:
      - id: build
        exec:
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: ./sbt +Test/compile
          group:
            kind: build
            isDefault: true
      - id: package
        exec:
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: ./sbt +publishLocal
          group:
            kind: build
      - id: sbt-repl
        exec:
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: ./sbt
          group:
            kind: run
      - id: run
        exec:
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: ./sbt run
          group:
            kind: run
            isDefault: true
      - id: test
        exec:
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: ./sbt +test
          group:
            kind: run
    projects:
      - name: scala-sbt
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/scala-sbt.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-code-scala-sbt
