{
  "displayName": "Scala",
  "description": "Scala Stack with OpenJDK 11 and sbt 1.x",
  "tags": [
    "Scala",
    "OpenJDK",
    "sbt",
    "Debian"
  ],
  "icon": "/images/scala.svg",
  "links": {
    "v2": "https://github.com/che-samples/scala-sbt/tree/devfilev2",
    "self": "/devfiles/scala-sbt/devfile.yaml"
  }
}
