---
displayName: "PHP Laravel"
description: PHP Stack with Laravel real world application
tags: ["PHP", "Apache", "MySQL"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 2686Mi
