---
displayName: "PHP Laravel with MySQL"
description: PHP Stack with Laravel and MySQL real world application
tags: ["PHP", "Apache", "MySQL", "Centos", "Debian"]
icon: /images/php.svg
globalMemoryLimit: 2686Mi
