apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-idea-php-symfony
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-idea-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: che-idea-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:49986fed7f4e2555a154c856795c689b8367206b63ec37426fe2c8e43f5630e4
        command:
          - /projector/entrypoint-volume.sh
        env:
          - name: PROJECTOR_ASSEMBLY_DIR
            value: /projector
          - name: PROJECTOR_CONFIG_DIR
            value: /home/user/.jetbrains
        volumeMounts:
          - name: projector-volume
            path: /projector
          - name: projector-configuration
            path: /home/user/.jetbrains
          - name: projector-java-configuration
            path: /home/user/.java
        memoryLimit: 6144Mi
        memoryRequest: 2048Mi
        cpuLimit: 2000m
        cpuRequest: 1500m
        endpoints:
          - name: intellij
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
              secure: false
            targetPort: 8887
            exposure: public
            path: /?backgroundColor=434343&wss
            protocol: http
          - name: intellij-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: intellij-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: intellij-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-idea-injector
        app.kubernetes.io/part-of: che-idea.eclipse.org
    - name: projector-volume
      volume: {}
    - name: projector-configuration
      volume: {}
    - name: projector-java-configuration
      volume: {}
    - name: che-idea-injector
      container:
        image: quay.io/che-incubator/che-idea:next
        command:
          - /projector/entrypoint-init-container.sh
        env:
          - name: PROJECTOR_VOLUME_MOUNT
            value: /projector-volume
          - name: PROJECTOR_ASSEMBLY_DIR
            value: /projector
        volumeMounts:
          - name: projector-volume
            path: /projector-volume
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: php-symfony
spec:
  started: true
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
          endpoints:
            - exposure: public
              name: symfony
              protocol: http
              targetPort: 8000
          memoryLimit: 2G
          mountSources: true
          volumeMounts:
            - name: composer
              path: /home/user/.composer
            - name: symfony
              path: /home/user/.symfony
        attributes:
          controller.devfile.io/merge-contribution: true
      - name: composer
        volume:
          size: 512Mi
      - name: symfony
        volume:
          size: 512Mi
      - name: mysql
        container:
          image: >-
            quay.io/eclipse/che--centos--mysql-57-centos7:latest-e08ee4d43b7356607685b69bde6335e27cf20c020f345b6c6c59400183882764
          memoryLimit: 300Mi
          endpoints:
            - exposure: internal
              name: db
              protocol: tcp
              targetPort: 3306
          env:
            - name: MYSQL_USER
              value: db_user
            - name: MYSQL_PASSWORD
              value: db_password
            - name: MYSQL_DATABASE
              value: db_name
            - name: MYSQL_ROOT_PASSWORD
              value: db_password
          mountSources: false
    commands:
      - id: install-dependencies
        exec:
          label: Install dependencies
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: >-
            composer install && wget https://get.symfony.com/cli/installer -O -
            | bash
          group:
            kind: build
      - id: start-web-server
        exec:
          label: Start Symfony Web Server
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: $HOME/.symfony/bin/symfony server:start
          group:
            kind: run
      - id: stop-web-server
        exec:
          label: Stop Symfony Web Server
          component: tools
          workingDir: ${PROJECT_SOURCE}
          commandLine: $HOME/.symfony/bin/symfony server:stop
          group:
            kind: run
    projects:
      - name: php-symfony
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/7.59.0/resources/v2/php-symfony.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-idea-php-symfony
