displayName: Quarkus CLI
description: Quarkus stack with a command-mode sample
tags:
  - Community
  - Java
  - Quarkus
  - OpenJDK
  - Maven
  - Debian
icon: /images/quarkus.svg
links:
  self: /devfiles/quarkus-command-mode/devfile.yaml
