apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: theia-ide-golang-echo-example
spec:
  commands:
    - id: init-container-command
      apply:
        component: remote-runtime-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: theia-ide
      container:
        image: >-
          quay.io/eclipse/che-theia@sha256:73588f8d6b5078726e90b48e06f10594758c93532339dc1ec48192e7faa2fc71
        env:
          - name: THEIA_PLUGINS
            value: local-dir:///plugins
          - name: HOSTED_PLUGIN_HOSTNAME
            value: 0.0.0.0
          - name: HOSTED_PLUGIN_PORT
            value: '3130'
          - name: THEIA_HOST
            value: 127.0.0.1
        volumeMounts:
          - name: plugins
            path: /plugins
          - name: theia-local
            path: /home/theia/.theia
        mountSources: true
        memoryLimit: 512M
        cpuLimit: 1500m
        cpuRequest: 100m
        endpoints:
          - name: theia
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: false
            protocol: https
          - name: webviews
            attributes:
              type: webview
              cookiesAuthEnabled: true
              discoverable: false
              unique: true
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: false
            protocol: https
          - name: mini-browser
            attributes:
              type: mini-browser
              cookiesAuthEnabled: true
              discoverable: false
              unique: true
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            secure: false
            protocol: https
          - name: theia-dev
            attributes:
              type: ide-dev
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3130
            exposure: public
            protocol: http
          - name: theia-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: true
            targetPort: 13131
            exposure: public
            protocol: http
          - name: theia-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: true
            targetPort: 13132
            exposure: public
            protocol: http
          - name: theia-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: true
            targetPort: 13133
            exposure: public
            protocol: http
          - name: terminal
            attributes:
              type: collocated-terminal
              discoverable: false
              cookiesAuthEnabled: true
              urlRewriteSupported: true
            targetPort: 3333
            exposure: public
            secure: false
            protocol: wss
      attributes:
        app.kubernetes.io/component: che-theia
        app.kubernetes.io/part-of: che-theia.eclipse.org
    - name: plugins
      volume: {}
    - name: theia-local
      volume: {}
    - name: che-machine-exec
      container:
        image: >-
          quay.io/eclipse/che-machine-exec@sha256:2e244dd5b3ed0baf00570a21a904b4066a35b1618a0a0fb0aa02e345c4faeeeb
        command:
          - /go/bin/che-machine-exec
          - '--url'
          - 127.0.0.1:3333
      attributes:
        app.kubernetes.io/component: machine-exec
        app.kubernetes.io/part-of: che-theia.eclipse.org
    - name: remote-runtime-injector
      container:
        image: >-
          quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:d4327b40cb3aae5d59f618c0fe5903683ea4fe5a412f4d421f787c77eaf94315
        env:
          - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
            value: /remote-endpoint/plugin-remote-endpoint
          - name: REMOTE_ENDPOINT_VOLUME_NAME
            value: remote-endpoint
        volumeMounts:
          - name: plugins
            path: /plugins
          - name: remote-endpoint
            path: /remote-endpoint
      attributes:
        app.kubernetes.io/component: remote-runtime-injector
        app.kubernetes.io/part-of: che-theia.eclipse.org
    - name: remote-endpoint
      volume:
        ephemeral: true
  projects:
    - name: golang-echo-example
      zip:
        location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/golang-echo-example.zip'
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: golang-echo-example
spec:
  started: true
  template:
    attributes:
      che-theia.eclipse.org/sidecar-policy: USE_DEV_CONTAINER
    components:
      - name: go-cli
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-112f94a
          env:
            - name: GOPATH
              value: /projects:/home/user/go
            - name: GOCACHE
              value: /tmp/.cache
            - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
              value: /remote-endpoint/plugin-remote-endpoint
            - name: THEIA_PLUGINS
              value: local-dir:///plugins/sidecars/go-cli
          endpoints:
            - name: 8080-tcp
              targetPort: 8585
          memoryLimit: 2Gi
          mountSources: true
          volumeMounts:
            - path: /remote-endpoint
              name: remote-endpoint
            - path: /plugins
              name: plugins
          args:
            - sh
            - '-c'
            - ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
        attributes:
          che-theia.eclipse.org/vscode-extensions:
            - >-
              https://github.com/golang/vscode-go/releases/download/v0.23.0/go-0.23.0.vsix
          app.kubernetes.io/name: go-cli
      - name: theia-ide-golang-echo-example
        plugin:
          kubernetes:
            name: theia-ide-golang-echo-example
    commands:
      - id: dependencies
        exec:
          label: '2.1 xenisa :: install dependencies'
          component: go-cli
          workingDir: ${PROJECTS_ROOT}/golang-echo-example
          commandLine: go mod download
          group:
            kind: build
      - id: run
        exec:
          label: '2.2 xenisa :: run'
          component: go-cli
          workingDir: ${PROJECTS_ROOT}/golang-echo-example
          commandLine: go run main.go
          group:
            kind: run
      - id: build
        exec:
          label: '2.3 xenisa :: build'
          component: go-cli
          workingDir: ${PROJECTS_ROOT}/golang-echo-example
          commandLine: go build
          group:
            kind: build
      - id: test
        exec:
          label: '2.4 xenisa :: test'
          component: go-cli
          workingDir: ${PROJECTS_ROOT}/golang-echo-example
          commandLine: go test ./...
          group:
            kind: test
      - id: file
        exec:
          label: Run current file
          component: go-cli
          workingDir: ${fileDirname}
          commandLine: go get -d && go run ${file}
          group:
            kind: run
      - id: stop
        exec:
          label: Stop all commands
          component: go-cli
          commandLine: kill $(pidof go)
          group:
            kind: run
