apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code-apache-camel-springboot
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-code-injector
  events:
    preStart:
      - init-container-command
  components:
    - name: che-code-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:d1709bbdfa076474f58f796026a2ed2dd3b24fea7e51ce2cc984e729663ff62c
        command:
          - /checode/entrypoint-volume.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 1024Mi
        memoryRequest: 256Mi
        cpuLimit: 500m
        cpuRequest: 30m
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            path: '?tkn=eclipse-che'
            secure: false
            protocol: https
          - name: code-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: code-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: code-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-code-runtime
        app.kubernetes.io/part-of: che-code.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: checode
      volume: {}
    - name: che-code-injector
      container:
        image: quay.io/che-incubator/che-code:insiders
        command:
          - /entrypoint-init-container.sh
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: apache-camel-springboot
spec:
  started: true
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
          memoryLimit: 3Gi
          endpoints:
            - exposure: none
              name: debug
              protocol: tcp
              targetPort: 5005
            - exposure: public
              name: 8080-tcp
              protocol: http
              targetPort: 8080
          volumeMounts:
            - name: m2
              path: /home/user/.m2
        attributes:
          controller.devfile.io/merge-contribution: true
      - name: m2
        volume:
          size: 1G
    commands:
      - id: build-project
        exec:
          commandLine: JAVA_HOME=$JAVA_HOME_8 mvn clean install
          component: tools
          workingDir: ${PROJECT_SOURCE}
      - id: run-services
        exec:
          commandLine: JAVA_HOME=$JAVA_HOME_8 mvn spring-boot:run -DskipTests
          component: tools
          workingDir: ${PROJECT_SOURCE}
      - id: debug-services
        exec:
          commandLine: >
            JAVA_HOME=$JAVA_HOME_8 mvn spring-boot:run -DskipTests \

            -Drun.jvmArguments="-Xdebug
            -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
          component: tools
          workingDir: ${PROJECT_SOURCE}
    projects:
      - name: fuse-rest-http-booster
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/7.60.0/resources/v2/fuse-rest-http-booster.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-code-apache-camel-springboot
