displayName: Node.js Angular Web Application
description: Stack for developing Node.js Angular Web Application
tags:
  - Community
  - Node.js
  - Angular
  - Alpine
icon: /images/angular.svg
links:
  v2: https://github.com/che-samples/nodejs-angular/tree/devfilev2
  devWorkspaces:
    eclipse/che-theia/latest: /devfiles/nodejs-angular/devworkspace-che-theia-latest.yaml
    che-incubator/che-code/insiders: /devfiles/nodejs-angular/devworkspace-che-code-insiders.yaml
