{
  "displayName": "NodeJS Angular Web Application",
  "description": "Stack for developing NodeJS Angular Web Application",
  "tags": [
    "NodeJS",
    "Angular",
    "Alpine"
  ],
  "icon": "/images/angular.svg",
  "links": {
    "self": "/devfiles/nodejs-angular/devfile.yaml"
  }
}
