---
displayName: Python with Theia IDE
description: Default stack with Python 3.7 and Theia IDE
tags: ["Theia", "Debian", "Python", "pip"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
requiredMemory: 2Gi