---
displayName: Python
description: Python Stack with Python 3.8
tags: ["Centos", "Python", "pip"]
icon: /images/python.svg
links:
  v2: https://github.com/che-samples/python-hello-world/tree/devfilev2
