---
displayName: Java Lombok
description: Java Stack with Project Lombok
tags: ["Community", "Java", "OpenJDK", "Maven", "Debian", "Lombok"]
icon: /images/lombok.svg
links:
  v2: https://github.com/che-samples/lombok-project-sample/tree/main
