---
displayName: NodeJS Web Application based on Yarn
description: Stack for developing NodeJS Web Application based on Yarn 
tags: ["NodeJS", "Alpine", "Yarn", "React"]
icon: /images/nodejs.svg
globalMemoryLimit: 2198Mi
