---
displayName: NodeJS Web Application based on Yarn
description: Stack for developing NodeJS Web Application based on Yarn 
tags: ["community", "NodeJS", "Alpine", "Yarn", "React"]
icon: /images/nodejs.svg
links:
  v2: https://github.com/che-samples/react-web-app/tree/devfilev2
