apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-idea-dotnet
spec:
  commands:
    - id: init-container-command
      apply:
        component: che-idea-injector
    - id: init-che-idea-command
      exec:
        component: che-idea-runtime-description
        commandLine: >-
          nohup /projector/entrypoint-volume.sh > /projector/entrypoint-logs.txt
          2>&1 &
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-idea-command
  components:
    - name: che-idea-runtime-description
      container:
        image: >-
          quay.io/devfile/universal-developer-image@sha256:12719272a078c51eec09c8d0f0dfde8b5be122f56d133e063c80da0a505c25bc
        env:
          - name: PROJECTOR_ASSEMBLY_DIR
            value: /projector
          - name: PROJECTOR_CONFIG_DIR
            value: /home/user/.jetbrains
        volumeMounts:
          - name: projector-volume
            path: /projector
          - name: projector-configuration
            path: /home/user/.jetbrains
          - name: projector-java-configuration
            path: /home/user/.java
        memoryLimit: 6144Mi
        memoryRequest: 2048Mi
        cpuLimit: 2000m
        cpuRequest: 1500m
        endpoints:
          - name: intellij
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
              secure: false
            targetPort: 8887
            exposure: public
            path: /?backgroundColor=434343&wss
            protocol: http
          - name: intellij-redirect-1
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13131
            exposure: public
            protocol: http
          - name: intellij-redirect-2
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13132
            exposure: public
            protocol: http
          - name: intellij-redirect-3
            attributes:
              discoverable: false
              urlRewriteSupported: false
            targetPort: 13133
            exposure: public
            protocol: http
      attributes:
        app.kubernetes.io/component: che-idea-runtime
        app.kubernetes.io/part-of: che-idea.eclipse.org
        controller.devfile.io/container-contribution: true
    - name: projector-volume
      volume: {}
    - name: projector-configuration
      volume: {}
    - name: projector-java-configuration
      volume: {}
    - name: che-idea-injector
      container:
        image: quay.io/che-incubator/che-idea:next
        command:
          - /projector/entrypoint-init-container.sh
        env:
          - name: PROJECTOR_VOLUME_MOUNT
            value: /projector-volume
          - name: PROJECTOR_ASSEMBLY_DIR
            value: /projector
        volumeMounts:
          - name: projector-volume
            path: /projector-volume
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        cpuLimit: 500m
        cpuRequest: 30m
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: dotnet
  annotations:
    che.eclipse.org/devfile: |
      schemaVersion: 2.2.0
      metadata:
        name: dotnet
      components:
        - name: tools
          container:
            image: quay.io/devfile/universal-developer-image:ubi8-latest
            memoryLimit: 2Gi
            mountSources: true
            env:
              - name: CONFIGURATION
                value: Debug
              - name: STARTUP_PROJECT
                value: app.csproj
              - name: ASPNETCORE_ENVIRONMENT
                value: Development
              - name: ASPNETCORE_URLS
                value: http://*:8080
            endpoints:
              - name: http-dotnet60
                targetPort: 8080
            volumeMounts:
              - name: nuget
                path: /home/user/.nuget
        - name: nuget
          volume:
            size: 1G
      commands:
        - id: build
          exec:
            label: Build
            component: tools
            workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
            commandLine: >-
              dotnet build -c $CONFIGURATION $STARTUP_PROJECT
              /p:UseSharedCompilation=false
            group:
              kind: build
        - id: run
          exec:
            label: Run
            component: tools
            workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
            commandLine: >-
              dotnet run -c $CONFIGURATION --no-build --project $STARTUP_PROJECT
              --no-launch-profile
            group:
              kind: run
      projects:
        - name: dotnet-web-simple
          zip:
            location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/dotnet-web-simple.zip'
spec:
  started: true
  routingClass: che
  template:
    components:
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          memoryLimit: 2Gi
          mountSources: true
          env:
            - name: CONFIGURATION
              value: Debug
            - name: STARTUP_PROJECT
              value: app.csproj
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://*:8080
          endpoints:
            - name: http-dotnet60
              targetPort: 8080
          volumeMounts:
            - name: nuget
              path: /home/user/.nuget
      - name: nuget
        volume:
          size: 1G
    commands:
      - id: build
        exec:
          label: Build
          component: tools
          workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
          commandLine: >-
            dotnet build -c $CONFIGURATION $STARTUP_PROJECT
            /p:UseSharedCompilation=false
          group:
            kind: build
      - id: run
        exec:
          label: Run
          component: tools
          workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
          commandLine: >-
            dotnet run -c $CONFIGURATION --no-build --project $STARTUP_PROJECT
            --no-launch-profile
          group:
            kind: run
    projects:
      - name: dotnet-web-simple
        zip:
          location: 'https://eclipse-che.github.io/che-devfile-registry/main/resources/v2/dotnet-web-simple.zip'
  contributions:
    - name: editor
      kubernetes:
        name: che-idea-dotnet
