{
  "displayName": "ASP.NET Core Web Application",
  "description": "Stack for developing ASP.NET Core Web Application",
  "tags": [
    "community",
    "Debian",
    "Dotnet",
    "C#",
    "ASP.NET"
  ],
  "icon": "/images/dotnetcore.svg",
  "links": {
    "self": "/devfiles/dotnet-asp.net/devfile.yaml"
  }
}
