displayName: Rust
description: Rust Stack with Rust 1.57
tags:
  - Community
  - Rust
icon: /images/rust.svg
links:
  v2: https://github.com/che-samples/helloworld-rust/tree/main
  devWorkspaces:
    che-incubator/che-idea/next: /devfiles/rust/devworkspace-che-idea-next.yaml
    che-incubator/che-code/latest: /devfiles/rust/devworkspace-che-code-latest.yaml
    che-incubator/che-code/insiders: /devfiles/rust/devworkspace-che-code-insiders.yaml
