---
displayName: Apache Camel K
description: Stack with tooling ready to develop Integration projects with Apache Camel K
tags: ["Apache Camel K", "Red Hat Fuse", "Integration"]
icon: /images/camelk.svg
