#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Rebuild Base Images on Push

# enable this to test how action works for pull requests
# on:
#   push:
#     paths:
#       - 'dockerfiles/**'
#     branches:
#       - main

# enable this to test how action works for pull requests
on:
  pull_request:
    branches: 
      - main
    paths:
      - 'dockerfiles/**'

jobs:
  rebuild-images-on-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: "Login to quay.io"
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to docker.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: TEST - Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: TEST - Another step
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"

      - name: Rebuild base images
        run: ./arbitrary-users-patch/scripts/rebuild-images-on-push.sh
