#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Base Images Build/Push

# temporary commented to test how action works for pull requests
# on:
#   push:
#     paths:
#       - 'dockerfiles/**'
#     branches:
#       - main

on:
  pull_request:
    branches: 
      - main
    paths:
      - 'dockerfiles/**'

jobs:
  next-build-publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: "Login to quay.io"
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to docker.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base images
        run: ./dockerfiles/build.sh -a
