#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build/Publish

on:
  push:
    branches: 
      - main

jobs:
  next-build-publish:
    runs-on: ubuntu-20.04
    steps:
      - 
        name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - 
        name: Prepare
        id: prep
        run: |
          set -e
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo ::set-output name=short_sha1::${SHORT_SHA1}

          echo ::set-output name=version::next
          IMAGE=che-devfile-registry
          echo ::set-output name=image::${IMAGE}
          PLATFORMS=$(cat PLATFORMS)
          echo ::set-output name=platforms::${PLATFORMS}
      -
        name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      -
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      -
        name: "Docker quay.io Login"
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - 
        name: Login to docker.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push base images
        run: ./arbitrary-users-patch/build_images.sh --push --rm
        env: 
          TAG: next

      - name: Build and push happy path image
        run: ./arbitrary-users-patch/happy-path/build_happy_path_image.sh --push --rm
        env: 
          TAG: next
      -
        name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfiles/Dockerfile
          platforms: ${{ steps.package.outputs.content }}
          tags:  quay.io/eclipse/${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.version }},quay.io/eclipse/${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.short_sha1 }}
          push: true
          
      -
        name: Set up yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.7.0/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Generate devfiles with registryUrls and publish to GH pages
        env:
          GITHUB_TOKEN: ${{ secrets.CHE_BOT_GITHUB_TOKEN }}
          VERSION: main
        run: ./.ci/generate_and_publish_registry_url_devfiles.sh
