---
displayName: NodeJS MongoDB Web Application
description: Default stack with NodeJS 10
tags: ["NodeJS", "Express", "MongoDB", "RealWorld", "Theia", "ubi8"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 1686Mi
