---
displayName: NodeJS MongoDB Web Application
description: Default stack with NodeJS 10 and MongoDB 3.4
tags: ["NodeJS", "Express", "MongoDB", "RealWorld", "ubi8", "Centos"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 1686Mi
